### ISSUE TITLE
关于用radius认证问题

### ISSUE THREAD

**Issue by SharkIng** [fanyueciyuan/eazy-for-ss#1]
按理说现在ocserv支持原生支持radius认证了，可是用您的安装脚本安装了之后设置auth=radius 后启动报错，知道是为什么么？

**Comment by liyangyijie** [comment]
0.6没有添加radius支持。如果想要的话，需要事先自己编译。可以使用下面命令自己编译freeradius-client-1.1.7,然后再运行该脚本重装即可。以后版本会写进去的。
```
wget -c ftp://ftp.freeradius.org/pub/freeradius/freeradius-client-1.1.7.tar.gz
tar -zxf freeradius-client-1.1.7.tar.gz
cd freeradius-client-1.1.7
./configure --prefix=/usr --sysconfdir=/etc
make -j"$(nproc)" && make install
cd ..
rm -rf freeradius-client*```
```
这样执行文件/usr/sbin/radiusclient 配置文件在/etc/radiusclient

**Comment by SharkIng** [comment]
好的，非常感谢，我试试看

原本自己上应该已经安装了radius client，不过也许是编译问题我重新编译下试试看

**Comment by liyangyijie** [comment]
ocserv 支持freeradius-client-1.1.7以及以上版本
