### ISSUE TITLE
Doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by williclarkam** [fanyueciyuan/eazy-for-ss#11]
Hello, 

Unfortunatly this script doesn't work on the latest version of Ubuntu 16.04 Xenial Xerus.
`ERROR: Sorry, your system is too old or has not been tested. `

**Comment by liyangyijie** [comment]
Hi,
Now，it's ok.
https://github.com/fanyueciyuan/eazy-for-ss/blob/master/ocservauto/ocservauto.sh#L974

**Comment by williclarkam** [comment]
Thanks man, works perfectly
