### ISSUE TITLE
boot from start failed

### ISSUE THREAD

**Issue by kt1024** [fanyueciyuan/eazy-for-ss#12]
搬瓦工, 已安装nginx/ss/pptp. 尝试以下命令时出错.

root@www:~# sudo insserv ocserv
insserv: warning: script 'wide-dhcpv6-client' missing LSB tags and overrides
insserv: warning: script 'bind9' missing LSB tags and overrides
insserv: There is a loop between service nginx and bind9 if stopped
insserv:  loop involving service bind9 at depth 2
insserv:  loop involving service nginx at depth 1
insserv: exiting now without changing boot order!

root@www:~# uname -a
Linux www 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
root@www:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by liyangyijie** [comment]
update-rc.d ocserv defaults

**Comment by kt1024** [comment]
成功, 谢谢.
