### ISSUE TITLE
请教goproxy-vps/自己证书的问题

### ISSUE THREAD

**Issue by luckypoem** [fanyueciyuan/eazy-for-ss#19]
我按https://pastebin.com/raw/QUPuM4L6  修改了我服务器上的goproxy-vps.toml文件，然后运行./goproxy-vps.sh start ，显示ok。没运行客户端，只是加了chrome的switchyomega的情景模式，内容为：
代理协议为https ,代理服务器的值为mydomain.com ,
代理端口为443 ，但在cr  中访问国内网站显示我的https://mydomain.com  的内容；访问http链接的被封网站也显示我的https://mydomain.com  的内容；访问https链接的被封网站,则显示“无法访问此网站”。
怎么回事呢？如何解决？可否专门写篇使用用户自己的证书情形下，如何用goproxy-vps翻墙的详细文章？

因为评论里这样沟通，怕漏了些什么关键的东西.

**Comment by luckypoem** [comment]
在这里https://www.fanyueciyuan.info/fq/goproxy-vps-443.html/comment-page-1#comment-675，无法留言成功

**Comment by ddzzhen** [comment]
域名转发很多时候都不好用，国外申请的免费域名即便网页可以正常转发，vpn也还是不能用的。
其它的我也帮不了你，并没有proxy，不好意思~



发件人: luckypoem
发送时间: 2017年8月7日 16:43
收件人: fanyueciyuan/eazy-for-ss
抄送: Subscribed
主题: Re: [fanyueciyuan/eazy-for-ss] 请教goproxy-vps/自己证书的问题 (#19)

在这里https://www.fanyueciyuan.info/fq/goproxy-vps-443.html/comment-page-1#comment-675，无法留言成功

**Comment by liyangyijie** [comment]
See https://github.com/phuslu/gop/issues/1470
