### ISSUE TITLE
客户端无法连接到服务器

### ISSUE THREAD

**Issue by WilliamZhang515** [fanyueciyuan/eazy-for-ss#2]
博主您好，小白一枚。 客户端无法连接到服务器，重启服务显示：
root@default:~#  /etc/init.d/ocserv restart
Restarting OpenConnect VPN Server: 
Stopping OpenConnect VPN Server Daemon: ...
[ok]
Starting OpenConnect VPN Server Daemon: iptables v1.4.14: invalid mask `255.255.' specified
Try `iptables -h' or 'iptables --help' for more information.
' specified.4.14: invalid mask `255.255.255.0
Try `iptables -h' or 'iptables --help' for more information.
' specified.4.14: invalid port/service `999
Try `iptables -h' or 'iptables --help' for more information.
" does not resolve to anything.

Try `iptables -h' or 'iptables --help' for more information.
...
Setting 'plain' as primary authentication method
Unknown user: nobody
[ok]
root@default:~# 

请问如何处理？谢谢～

**Comment by liyangyijie** [comment]
用下面的命令 看看你的配置文件
```
cat /etc/ocserv/ocserv.conf |grep -v ^#| sed /^$/d|grep ipv4
```
确认会有如下显示
```
ipv4-network = 192.168.10.0
ipv4-netmask = 255.255.255.0
```

然后
```
cat /etc/ocserv/start-ocserv-sysctl.sh
```
请贴出上面命令之后的显示内容，谢谢

**Comment by WilliamZhang515** [comment]
root@default:~# cat /etc/ocserv/start-ocserv-sysctl.sh
#!/bin/bash

#vars
OCSERV_CONFIG="/etc/ocserv/ocserv.conf"

# turn on IP forwarding
#sysctl -w net.ipv6.conf.all.forwarding=1 > /dev/null 2>&1
sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1

#get gateway and profiles
gw_intf_oc=`ip route show|sed -n 's/^default.* dev \([^ ]*\).*/\1/p'`
ocserv_tcpport=`sed -n 's/^tcp-.*=[ \t]*//p' $OCSERV_CONFIG`
ocserv_udpport=`sed -n 's/^udp-.*=[ \t]*//p' $OCSERV_CONFIG`
ocserv_ip4_work_mask=`sed -n 's/^ipv4-.*=[ \t]*//p' $OCSERV_CONFIG|sed 'N;s|\n|/|g'`

# turn on NAT over default gateway and VPN
if !(iptables-save -t nat | grep -q "$gw_intf_oc (ocserv)"); then
iptables -t nat -A POSTROUTING -s $ocserv_ip4_work_mask -o $gw_intf_oc -m comment --comment "$gw_intf_oc (ocserv)" -j MASQUERADE
fi

if !(iptables-save -t filter | grep -q "$gw_intf_oc (ocserv2)"); then
iptables -A FORWARD -s $ocserv_ip4_work_mask -m comment --comment "$gw_intf_oc (ocserv2)" -j ACCEPT
fi

if !(iptables-save -t filter | grep -q "$gw_intf_oc (ocserv3)"); then
iptables -A INPUT -p tcp --dport $ocserv_tcpport -m comment --comment "$gw_intf_oc (ocserv3)" -j ACCEPT
fi

if [ "$ocserv_udpport" != "" ]; then
    if !(iptables-save -t filter | grep -q "$gw_intf_oc (ocserv4)"); then
        iptables -A INPUT -p udp --dport $ocserv_udpport -m comment --comment "$gw_intf_oc (ocserv4)" -j ACCEPT
    fi
fi

# turn on MSS fix
# MSS = MTU - TCP header - IP header
if !(iptables-save -t mangle | grep -q "$gw_intf_oc (ocserv5)"); then
iptables -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "$gw_intf_oc (ocserv5)" -j TCPMSS --clamp-mss-to-pmtu
fi

echo "..."
 
^_^

**Comment by liyangyijie** [comment]
首先，感谢你的反馈。
有问题，大家一起解决，我也是玩linux几天而已。

你这里貌似没有nobody这个用户，所以先添加一个。
```
 useradd -G nogroup nobody
```
然后请执行下面的命令里换一下ip池书写方式，
```
sed -i 's/ipv4-.*/#&/' /etc/ocserv/ocserv.conf
sed -i 's/^#\(ipv4.*work.*\.0\)/\1\/24/' /etc/ocserv/ocserv.conf
```
重启一下ocserv试试。

====

如果还报错，不能正常使用的话，
1，好吧，使用下面的命令把系统环境输入的log文件。
```
 uname -a >> log && cat /etc/issue >>log
```
2，把你的ocserv全部有效配置，用下面的命令输入到log文件。
```
cat /etc/ocserv/ocserv.conf|grep -v ^#|sed /^$/d|sed /domain/d|sort >> log
```

3，使用下面的命令把已经被占用的内网网段输入到log文件。
```
 ifconfig|grep 'inet '|grep -v $(wget -qO- ipv4.icanhazip.com) >> log
```
4，最后看一下log
```
cat log
```
请贴出上面命令之后的显示内容，再次谢谢！

**Comment by WilliamZhang515** [comment]
嗯，继续报错...... 
    Linux default 2.6.32-042stab104.1 #1 SMP Thu Jan 29 12:58:41 MSK 2015 i686 GNU/Linux
    Debian GNU/Linux 7 \n \l


    auth = "plain[passwd=/etc/ocserv/ocpasswd]"
    auth-timeout = 40
    cisco-client-compat = true
    compression = true
    cookie-timeout = 300
    deny-roaming = false
    device = vpns
    dns = 8.8.4.4
    dns = 8.8.4.4
    dpd = 90
    idle-timeout = 1200
    ipv4-network = 192.168.10.0/24
    isolate-workers = false
    keepalive = 32400
    max-clients = 160
    max-same-clients = 0
    mobile-dpd = 1800
    mobile-idle-timeout = 2400
    output-buffer = 2000
    pid-file = /var/run/ocserv.pid
    ping-leases = false
    predictable-ips = true
    rekey-method = ssl
    rekey-time = 172800
    run-as-group = nogroup
    run-as-user = nobody
    server-cert = /etc/ocserv/server-cert.pem
    server-key = /etc/ocserv/server-key.pem
    socket-file = /var/run/ocserv-socket
    tcp-port = 999
    tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0"
    try-mtu-discovery = true
    udp-port = 20
    use-occtl = true
    use-utmp = true
              inet addr:127.0.0.1  Mask:255.0.0.0
              inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255

麻烦了 ^^;

**Comment by liyangyijie** [comment]
根据你的配置，可以执行下面的静态命令来试试。
```shell
gw_intf_oc=`ip route show|sed -n 's/^default.* dev \([^ ]*\).*/\1/p'`
iptables -t nat -A POSTROUTING -s 192.168.10.0/24 -o $gw_intf_oc  -j MASQUERADE
iptables -A FORWARD -s 192.168.10.0/24 -j ACCEPT
iptables -A INPUT -p tcp --dport 999 -j ACCEPT
iptables -A INPUT -p udp --dport 20 -j ACCEPT
iptables -A FORWARD  -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```
如果没有错误的话，那么可以执行下面的命令。
```
wget https://raw.githubusercontent.com/fanyueciyuan/eazy-for-ss/master/ocservauto/samiptables -O /etc/ocserv/start-ocserv-sysctl.sh
```
然后重启一下ocserv试试。

====

如果还是有错误显示的话，那么重新安装一下iptables
```
apt-get remove --purge iptables -y
apt-get autoremove
apt-get autoclean
apt-get clean
apt-get install iptables
```

====

**Comment by WilliamZhang515** [comment]
我今天又重新安装了一遍，成功了，感谢

**Comment by liyangyijie** [comment]
好的。
