### ISSUE TITLE
按照教程添加组用户All，Route，iphone客户端连接不上啊

### ISSUE THREAD

**Issue by loveser** [fanyueciyuan/eazy-for-ss#3]
服务器debug信息显示如下：
ocserv[2100]: sec-mod: using 'plain' authentication to authenticate user (session: kj+bJ)
ocserv[2100]: user 'xiaolu123' requested group 'Route' but is not a member
ocserv[2100]: sec-mod: error processing data for 'sm: auth init' command (-1)
ocserv[2105]: worker[xiaolu123]: 183.16.89.35 worker-auth.c:1403: failed authentication for 'xiaolu123'
ocserv[2099]: main: 183.16.89.35:10207 user disconnected
请大神帮看看什么原因啊

**Comment by liyangyijie** [comment]
ocpasswd -c /etc/ocserv/ocpasswd  -g "Route，All" username
请确保用户名在Route和All组

**Comment by loveser** [comment]
这个我有执行的啊我是按照
https://github.com/fanyueciyuan/eazy-for-ss/blob/master/ocservauto/plain-ca-group.md这个来做的，客户端连不上，服务器就是报的以上信息

**Comment by liyangyijie** [comment]
请查看一下 /etc/ocserv/ocpasswd 文件内容
`
cat  /etc/ocserv/ocpasswd
`
形式应该是这样
`
用户名:Route,All:加密字符串
`
那个教程里面的逗号（中文）用错了，已经修改为英文逗号了。
使用下面的命令来重定一下即可
`
ocpasswd -c /etc/ocserv/ocpasswd -g "Route,All" username
`

**Comment by loveser** [comment]
非常感谢，已经解决，现在可以愉快的穿墙了
