### ISSUE TITLE
关于锐速加速配置

### ISSUE THREAD

**Issue by OrangeYoung** [fanyueciyuan/eazy-for-ss#4]
/serverspeeder/etc/config 配置单中，accif="eth0" 能否加速成功？还是必须要：accif="eth0 vpns1"
Linode 下有这个bug：kernel:unregister_netdevice: waiting for vpns0 to become free. Usage count = 1 一直出现

**Comment by liyangyijie** [comment]
http://bbs.tcp.hk/thread-27-1-1.html
使用tun的vpn 必须得加上根据官方的说法。

根据https://www.v2ex.com/t/172292后面的几个帖子，貌似是disconnect-script执行顺序有些问题。
所以，折中一下在/etc/ocserv/ocserv.conf中只取消connect-script注释，修改如下：
connect-script = /etc/ocserv/Speeder_reload.sh
#disconnect-script = /etc/ocserv/Speeder_reload.sh

**Comment by OrangeYoung** [comment]
@liyangyijie 非常感谢你的回答。
