### ISSUE TITLE
锐速应该怎样配置才不会报这个错误？

### ISSUE THREAD

**Issue by OrangeYoung** [fanyueciyuan/eazy-for-ss#5]
Message from syslogd@li860-159 at Aug 21 10:34:25 ...
kernel:unregister_netdevice: waiting for vpns0 to become free. Usage count = 1

锐速修改了advinacc="1", maxmode="1", rsc="1" 按照作者的步骤配置了AnyConnect 加速，有这样的错误。

**Comment by liyangyijie** [comment]
我的这个方法是个折中的办法，断线之后，tun设备就下线了，自然会出现错误日志，但不至于锐速崩溃。
但是，如果想要执行disconnect脚本的话，会导致锐速在vpn自动重连时候崩溃。

**Comment by OrangeYoung** [comment]
@liyangyijie 恩，谢谢。
