### ISSUE TITLE
关于您提到的chnroutes路由表一个小疑问

### ISSUE THREAD

**Issue by zpljd258** [fanyueciyuan/eazy-for-ss#6]
之前不是一直有消息提到anyconnect for IOS只能支持到最大200条路由.我看您最新的脚本也说取消了这个限制.是否是现在能支持到超过200路由表了呢?

希望您能解答这个疑问.非常感谢您的脚本对我帮助非常大,这里跟您再说一次感谢!

**Comment by liyangyijie** [comment]
取消限制的是服务端，客户端还是有限制的。anyconnect for IOS依然只能支持到最大200条路由。

**Comment by zpljd258** [comment]
很抱歉回复延迟。非常感谢您的解答。谢谢
