### ISSUE TITLE
获得chinadomains的域名并填充到pdnsd.conf有错误

### ISSUE THREAD

**Issue by hdstar2009** [fanyueciyuan/eazy-for-ss#7]
wget -qO- http://git.io/jkgU --no-check-certificate|grep -v ^#|cut -d/ -f2|sed s/^/./ > chinadomains

获得的chinadomains都是形如.taobao.com这样的

但是pdnsd.conf下的域名是形如.taobao.com,

所以最后执行替换获得的pdnsd.conf里面的域名全是参数错误的，pdnsd无法运行

**Comment by liyangyijie** [comment]
额，已经修复了。
