### ISSUE TITLE
tcp和udp用同一个端口和用不同的端口对速度的影响差距比较明显吗？

### ISSUE THREAD

**Issue by newyorkzone** [fanyueciyuan/eazy-for-ss#8]

**Comment by newyorkzone** [comment]
如果同时使用tcp和udp的话，应该是自动使用upd的吗？只是用tcp建立初期的连接？那用同一个端口和用不同的段口是完全一样的吗？也没什么影响？tcp和udp也不在同一时间使用端口的？

**Comment by liyangyijie** [comment]
> The server maintains two connections/channels with the client. The main VPN channel is established over TCP, HTTP and TLS. This is the control channel as well as the backup data channel. After its establishment a UDP channel using DTLS is initiated which serves as the main data channel. If the UDP channel fails to establish or is temporarily unavailable the backup channel over TCP/TLS is being used.

简言之，TCP（HTTP+TLS）主要是用来建立VPN通道、进行数据控制，其次才是作为数据传输的备用方式；UDP（DTLS）则是主要的数据传输方式。

TCP、UDP端口可以一样也可以不一样。UDP建议选择合适自己的端口，谨防ISP限速、封锁。

如果不想使用UDP（例如ISP对全部UDP端口限速严重），注释掉配置文件中的UDP端口项目即可，一般情况下，单TCP模式ocserv的效率较低。

**Comment by newyorkzone** [comment]
好的 非常的感谢
