### ISSUE TITLE
FreeRADIUS 3.0.X

### ISSUE THREAD

**Issue by williclarkam** [fanyueciyuan/eazy-for-ss#9]
Hello Sir, 

I greatly greatly appreciate your outstanding work. The only way I could get OpenConnect to work, was using this script. Thank you. Just I was wondering, is there any reason, why you Sir chose to use FreeRADIUS v.1.0.X?

Thanks again for you awesome work.

**Comment by liyangyijie** [comment]
Hi,
It requires FreeRADIUS Client Library( [freeradius-client](http://freeradius.org/freeradius-client/) or  [radcli](https://github.com/radcli/radcli) ) .
Thanks  for your question.

**Comment by williclarkam** [comment]
Oh, yes, you are right my mistake. 
Just I have another question, are you Sir using FreeRADIUS 3.0.11? Because I saw that this version is the latest one. I am sorry if my question is stupid. 
Thanks for your amazing work Sir.

**Comment by liyangyijie** [comment]
Sorry，
In fact , I did not used RADIUS authentication for ocserv.
But I suggest you use the latest version.

**Comment by williclarkam** [comment]
Thank you Sir, I definitely will follow your advise. 
Thanks for everything
